spring:
  profiles:
    active: dev
  datasource:
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        event:
          merge:
            entity_copy_observer: allow
    show-sql: false
    hibernate:
      ddl-auto: update